spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: 'jdbc:mysql://localhost:3308/db-social'
    username: sys
    password: hj125kl
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
#spring.jpa.show-sql: true
